In [1]:
a=arange(5)
print (a)

NameError: name 'arange' is not defined

In [24]:
from datetime import datetime
import numpy as np
start=datetime.now()

#b=8*8 matrix with all the values zero
b=np.zeros(64,dtype="uint64").reshape(8,8)

#replacing alternative coloumns with 1
b[:,::2]=1

#a is the last column
a=b[:,-1].reshape(8,1)

print(b)

end_time=datetime.now()-start

print(end_time)


[[1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]]
0:00:00.002002


In [28]:
#different size 

from datetime import datetime
import numpy as np
start=datetime.now()

#b=8*8 matrix with all the values zero
b=np.zeros(64,dtype="uint32").reshape(8,8)

#replacing alternative coloumns with 1
b[:,::2]=1

#a is the last column
a=b[:,-1].reshape(8,1)

print(b)

end_time=datetime.now()-start

print(end_time)


[[1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]]
0:00:00.002002
