In [1]:
import numpy as np

m=np.array([np.arange(2),np.arange(2)])
print (m)
print(m.shape)

[[0 1]
 [0 1]]
(2, 2)


In [2]:
import numpy as np

m=np.array([np.arange(2),np.arange(2)])
print (m)
print(m.shape)

[[0 1]
 [0 1]]
(2, 2)


In [12]:
import numpy as np

"""m=np.array([np.arange(2),np.arange(2)])
print (m)
print(shape.m)"""

b=np.arange(24).reshape(2,3,4)

print(b)
print(b[0,1,::2])
print(b[0,:,3])
print(b[:,1])



[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[4 6]
[ 3  7 11]
[[ 4  5  6  7]
 [16 17 18 19]]


In [ ]:
lis1=[1,3,4,5]
lis2=lis1[:]
lis=[]
for num in lis1:
    for num2 in lis2:
        lis.append(num1,num2)

In [ ]:
while x!=10:
    for num1 in lis_int:
        for num2 in lis2:
            for num3 in lis3:
                sample=(num1,num2,num3)
                final_lis.append(sample)
                x+=1
                print(sample)

In [ ]:
lis1=[1,2,3,4,5]
lis2=lis1[:]
lis=[]
for num in lis1:
    for num2 in lis2:
        sample=(num,num2)
        lis.append(sample)
print(lis)


In [ ]:
lis1=[1,2,3,4,5]
lis2=lis1[:]
lis=[]
for num1 in lis1:
    for num2 in lis2:
        if num1!=num2:
            sample=(num1,num2)
            lis.append(sample)
            

In [13]:
import numpy as np
a=np.arange(36).reshape(2,6,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

In [15]:
b=a[0]
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [16]:
c=a[1]

In [17]:
c

array([[18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35]])

In [18]:
b+c

array([[18, 20, 22],
       [24, 26, 28],
       [30, 32, 34],
       [36, 38, 40],
       [42, 44, 46],
       [48, 50, 52]])

In [19]:
hstack(b,c)

NameError: name 'hstack' is not defined

In [29]:
np.dstack((b,c))

array([[[ 0, 18],
        [ 1, 19],
        [ 2, 20]],

       [[ 3, 21],
        [ 4, 22],
        [ 5, 23]],

       [[ 6, 24],
        [ 7, 25],
        [ 8, 26]],

       [[ 9, 27],
        [10, 28],
        [11, 29]],

       [[12, 30],
        [13, 31],
        [14, 32]],

       [[15, 33],
        [16, 34],
        [17, 35]]])

In [33]:
cdc=np.hstack((b,c))
cdc

array([[ 0,  1,  2, 18, 19, 20],
       [ 3,  4,  5, 21, 22, 23],
       [ 6,  7,  8, 24, 25, 26],
       [ 9, 10, 11, 27, 28, 29],
       [12, 13, 14, 30, 31, 32],
       [15, 16, 17, 33, 34, 35]])

In [34]:
cdc[1:3]=[0]

In [35]:
cdc

array([[ 0,  1,  2, 18, 19, 20],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 9, 10, 11, 27, 28, 29],
       [12, 13, 14, 30, 31, 32],
       [15, 16, 17, 33, 34, 35]])

In [39]:
np.hsplit(cdc,3)

[array([[ 0,  1],
        [ 0,  0],
        [ 0,  0],
        [ 9, 10],
        [12, 13],
        [15, 16]]), array([[ 2, 18],
        [ 0,  0],
        [ 0,  0],
        [11, 27],
        [14, 30],
        [17, 33]]), array([[19, 20],
        [ 0,  0],
        [ 0,  0],
        [28, 29],
        [31, 32],
        [34, 35]])]

In [40]:
np.vsplit(cdc,2)

[array([[ 0,  1,  2, 18, 19, 20],
        [ 0,  0,  0,  0,  0,  0],
        [ 0,  0,  0,  0,  0,  0]]), array([[ 9, 10, 11, 27, 28, 29],
        [12, 13, 14, 30, 31, 32],
        [15, 16, 17, 33, 34, 35]])]

In [41]:
cdc.ndim

2

In [44]:
cdc

array([[ 0,  1,  2, 18, 19, 20],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 9, 10, 11, 27, 28, 29],
       [12, 13, 14, 30, 31, 32],
       [15, 16, 17, 33, 34, 35]])

In [46]:
np.savetxt("cdc.txt",cdc)

In [47]:
cdc


array([[ 0,  1,  2, 18, 19, 20],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 9, 10, 11, 27, 28, 29],
       [12, 13, 14, 30, 31, 32],
       [15, 16, 17, 33, 34, 35]])