In [ ]:
import numpy as np

a=np.array(np.arange(9)).reshape(3,3)
b=2*a
print (a)
print (b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [1]:
zx=np.dstack((a,b))

NameError: name 'np' is not defined

In [2]:
np.column_stack(a,b)

NameError: name 'np' is not defined

In [9]:
oned=np.arange(7)
twice=2*oned
np.column_stack((oned,twice))

array([[ 0,  0],
       [ 1,  2],
       [ 2,  4],
       [ 3,  6],
       [ 4,  8],
       [ 5, 10],
       [ 6, 12]])

In [10]:
print(oned)
print(twice)

[0 1 2 3 4 5 6]
[ 0  2  4  6  8 10 12]


In [11]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [13]:
h_split=np.hsplit(a,3)

[array([[0],
        [3],
        [6]]), array([[1],
        [4],
        [7]]), array([[2],
        [5],
        [8]])]

In [16]:
type(h_split)

NameError: name 'h_split' is not defined

In [17]:
h_split=np.hsplit(a,3)
print(type(h_split))

<class 'list'>


In [18]:
print(h_split[1])

[[1]
 [4]
 [7]]


In [19]:
for arrays in h_split:
    print(arrays)

[[0]
 [3]
 [6]]
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]


In [21]:
zx
xz

NameError: name 'zx' is not defined

In [22]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
np.vsplit(a,3)

[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]

In [33]:
a.nbytes

36

In [34]:
a.reshape(9,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [35]:
a.reize(9,1)

AttributeError: 'numpy.ndarray' object has no attribute 'reize'

In [36]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
a.resize(3,3)

In [40]:
a

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [41]:
a

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [43]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [44]:
gh=a

In [45]:
gh.tolist()

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [3]:
lis=[1,2,3,4,5,6,7]
lis[0:2]=5
print(lis)

TypeError: can only assign an iterable

In [ ]:
a=np.arange(32)
a

NameError: name 'np' is not defined

In [4]:
6+7

13