In [2]:
inp=input("enter your sample \n for e.g 1,45,6,7,4 \n")
#sample_size=int(input("enter your sample size"))

#appending the elements of input in lis
lis=inp.split(",")
lis_int=[]

final_lis=[]
x=0

for numbers in lis:
    lis_int.append(int(numbers))
lis2=lis_int[:]
for num1 in lis_int:
    for num2 in lis2:
        x += 1
        sample = (num1, num2,)
        # final_lis.append(sample)

        # calculate mean
        m = round(sum(sample) / len(sample), 2)

        # calculate variance using a list comprehension
        var_res = round(sum([(xi - m) ** 2 for xi in sample]) / len(sample), 2)
        # apending the final reults in the tuple for e.g
        # (1,2,3) , mean ,variance
        tup = (x, sample, m, var_res)
        final_lis.append(tup)
        print (tup)

StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

In [2]:
import numpy as np

#b=8*8 matrix with all the values zero
b=np.zeros(64,dtype="uint32").reshape(8,8)

#replacing alternative coloumns with 1
b[:,::2]=1

#a is the last column
a=b[:,-1].reshape(8,1)

print(b)







[[1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1 0]]


In [4]:
np.arange(4)


array([0, 1, 2, 3])

In [7]:
np.array([np.arange(3),np.arange(3)])

array([[0, 1, 2],
       [0, 1, 2]])

In [9]:
a=np.arange(42).reshape(6,7)
a

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41]])

In [16]:
b=a.reshape(2,3,7)
b

array([[[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25, 26, 27],
        [28, 29, 30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39, 40, 41]]])

In [18]:
#this is not a conventiona; multiplaction of matrix 
#element with the same i,j values are multiplying with each other
b[0]*b[1]

array([[  0,  22,  46,  72, 100, 130, 162],
       [196, 232, 270, 310, 352, 396, 442],
       [490, 540, 592, 646, 702, 760, 820]])

In [22]:
b[0,0,:]

array([0, 1, 2, 3, 4, 5, 6])

In [27]:
d=np.hstack((b[0],b[1]))
d

array([[ 0,  1,  2,  3,  4,  5,  6, 21, 22, 23, 24, 25, 26, 27],
       [ 7,  8,  9, 10, 11, 12, 13, 28, 29, 30, 31, 32, 33, 34],
       [14, 15, 16, 17, 18, 19, 20, 35, 36, 37, 38, 39, 40, 41]])

In [32]:
e=np.concatenate((b[0],b[1]),axis=0)
e

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41]])

In [36]:
np.hsplit(e,7)[0:3]

[array([[ 0],
        [ 7],
        [14],
        [21],
        [28],
        [35]]), array([[ 1],
        [ 8],
        [15],
        [22],
        [29],
        [36]]), array([[ 2],
        [ 9],
        [16],
        [23],
        [30],
        [37]])]

In [44]:
lis=[nums for nums in np.vsplit(e,3)]
print(len(lis))
for num in lis:
    print(num)

3
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]]
[[14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
[[28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]]


In [47]:
np.shape(np.hsplit(e,7))

(7, 6, 1)

In [48]:
np.size(np.shape(np.hsplit(e,7)))

3

In [25]:
import numpy as np
import datetime
# Monday 0
# Tuesday 1
# Wednesday 2
# Thursday 3
# Friday 4
# Saturday 5
# Sunday 6
def datestr2num(s):
    return datetime.datetime.strptime(s, "%d-%m-%Y").date().weekday()


SyntaxError: unexpected EOF while parsing (<ipython-input-25-dc7483bef7a7>, line 3)

In [ ]:
dates,price, close=np.loadtxt('prices.csv', delimiter=',', usecols=(0,2,3),
converters={1: datestr2num}, unpack=True, dtype='str')
price = np.asanyarray(price, 'd')
close = np.asanyarray(close, 'd')


print(price)
print(close)
print("Dates =", dates)

averages = np.zeros(5)
print("average",averages)
dates = list(map(dates2num, dates))
dates = np.asanyarray(dates,'f')
print("dates",dates)

NameError: name 'datestr2num' is not defined

In [5]:
print("hello")

hello


In [15]:
x=5
print("hello %x" %(x))

hello 5y


In [4]:

import datetime
def dates2num(s):
    return datetime.datetime.strptime(s, "%d-%m-%Y").date().weekday()
dates2num("2-3-2014")

6

In [8]:
dates, price, close=np.loadtxt('prices.csv', delimiter=',', usecols=(0,2,3), converters={1: dates2num}, unpack=True, dtype='str')
dates
dates=list(map(dates2num, dates))
dates=np.asanyarray(dates,'f')
dates

ValueError: time data "b'4/1/2010'" does not match format '%d-%m-%Y'

In [2]:
7+6


13

In [15]:
dates, price, close=np.loadtxt('prices.csv', delimiter=',', usecols=(0,2,3), converters={1: dates2num}, unpack=True, dtype='str')
close


array(["b'214.009998'", "b'214.379993'", "b'210.969995'", ...,
       "b'116.760002'", "b'116.730003'", "b'115.82'"], 
      dtype='<U13')

In [14]:
5+4

9

In [16]:
lis=np.tolist(dates)

AttributeError: module 'numpy' has no attribute 'tolist'

In [28]:
xn=[23,44,56,77,1,33,4556,90,6]
y=np.array(x)
returns=np.diff(y)/y[:-1]
postind=np.where(returns>0)
postind

(array([0, 1, 2, 4, 5], dtype=int64),)

In [29]:
np.take(returns,postind)

array([[   0.91304348,    0.27272727,    0.375     ,   32.        ,
         137.06060606]])

In [31]:
import datetime
def dates2num(s):
    return datetime.datetime.strptime(s, "%d-%m-%Y").date().weekday()

dates_a=np.array([28-1-2012,29-1-2012,30-1-2012,31-1-2012,1-2-2012,2-2-2012,3-2-2012],dtype=str)
conv_dates=list(map(dates2num,dates_a))
conv_dates

ValueError: time data '-1985' does not match format '%d-%m-%Y'

In [32]:
xn=[23,44,56,77,1,33,4556,90,6]
np.argmax(xn)

6

In [34]:
np.take(xn,6)

4556

In [4]:
import numpy as np
c=np.loadtxt('ppl.csv', delimiter=',', usecols=(3,), unpack=True)
c


array([ 114.5      ,  112.8499985,  114.5999985, ...,  175.5      ,
        175.5      ,  176.5      ])